base_url = "https://felixschloesser.de"

theme = "after-light"
compile_sass = true
title = "TinTins Website"
description = "A Website for a TinTIN"


taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "TinTin"
after_light_menu = [
    {url = "$BASE_URL", name = "Blog"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_light_title = "My blog"
